references:
  defaults: &defaults
    working_directory: ~/project
    docker:
      - image: circleci/node:8-browsers

  cache_key: &cache_key
    todo-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/

version: 2.1
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          key: *cache_key
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          name: Save cache
          key: *cache_key
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .ssh
  lint:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Check Prettier, ESLint, Flow
          command: yarn ci-check
  test:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Build
          command: yarn build
      - run:
          name: Visual Regression
          command: npx percy snapshot public
workflows:
  version: 2.1
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
            - lint
